apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: rzozookeeper
  name: rzozookeeper
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: rzozookeeper:latest
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/robbertvdzon/openshiftzookeeper.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift'
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
