server.port: 8091

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        question-in:
          destination: questionin
          contentType: application/json
        question-out:
          destination: questionout
          contentType: application/json