server.port: 8092

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        question-ask:
          destination: question-ask
          contentType: application/json
        question-ask-read:
          destination: question-ask
          contentType: application/json
        question-answer:
          destination: question-answer
          contentType: application/json