apiVersion: v1
kind: Service
metadata:
  name: rzokafka
  namespace: rzo-test
spec:
  ports:
  - name: 9092-tcp
    protocol: TCP
    port: 9092
    targetPort: 9092
  selector:
    deploymentconfig: "rzokafka"
  sessionAffinity: None
  type: ClusterIP
